### ISSUE TITLE
ArgumentOutOfRangeException in docker

### ISSUE THREAD

**Issue by Cherepoc** [w8tcha/BootstrapEmail.Net#41]
Hi!
I've been trying to use the library in docker, I get this error when running the container:
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at BootstrapEmail.Net.Compiler.GetEmbeddedCoreFiles()
   at BootstrapEmail.Net.Compiler..ctor(String input, ConfigStore config, InputType type)
   at BootstrapEmail.Net.BootstrapEmail.FileCompile(String relativeFilePath, String savePath)
   at BootstrapEmail.Net.BootstrapEmail.Compile(String input, String output, InputType type)
   at Program.<Main>$(String[] args) in /app/Program.cs:line 7
```
Here's a project. Run the docker.ps1 file in the powershell.
[BootstrapEmailExample.zip](https://github.com/w8tcha/BootstrapEmail.Net/files/15027383/BootstrapEmailExample.zip)

**Comment by w8tcha** [comment]
There is a path problem. But it appears that the libsass library doesn't work on linux or mac. Besides the fact that libsass is already depreactated.

So for the next release i switch to Dartsass. But this will require that if not windows is used you will need to manuall install the nuget package for the dart sass runtime

**Comment by Cherepoc** [comment]
Thanks! Tried the 1.5.0 version, still gives me errors
[BootstrapEmailExample.zip](https://github.com/w8tcha/BootstrapEmail.Net/files/15083986/BootstrapEmailExample.zip)
I used nuget to include the runtime, tried linux-64, and the linux-musl-64. The second says the sass was not found (I thought the musl package should work on alpine), the first one gives me the error below (same if non-alpine dotnet image is used):
` ---> System.IO.IOException: Broken pipe
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.SendAsync(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamWriter.<FlushAsyncInternal>g__Core|76_0(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.StreamWriter.<FlushAsyncInternal>g__Core|76_0(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)
   at System.IO.StreamWriter.FlushAsyncInternal(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)
   at System.IO.StreamWriter.WriteAsyncInternal(ReadOnlyMemory`1 source, Boolean appendNewLine, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.StreamWriter.WriteAsyncInternal(ReadOnlyMemory`1 source, Boolean appendNewLine, CancellationToken cancellationToken)
   at System.IO.StreamWriter.WriteAsync(String value)
   at Citizen17.DartSass.DartSassRuntime.ExecuteAsync(String args, String input, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Citizen17.DartSass.DartSassRuntime.ExecuteAsync(String args, String input, CancellationToken cancellationToken)
   at Citizen17.DartSass.DartSassCompiler.CompileCodeAsync(String code, SassCompileOptions options, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Citizen17.DartSass.DartSassCompiler.CompileCodeAsync(String code, SassCompileOptions options, CancellationToken cancellationToken)
   at BootstrapEmail.Net.SassCache.CompileAndCacheScss(String cachePath)
   at BootstrapEmail.Net.SassCache.Compile()
   at BootstrapEmail.Net.SassCache.Compile(String type, Config config, StyleType style)
   at BootstrapEmail.Net.Compiler.InlineCss()
   at BootstrapEmail.Net.Compiler.PerformHtmlCompile()
   at BootstrapEmail.Net.Compiler.PerformFullCompile()
   at BootstrapEmail.Net.BootstrapEmail.FileCompile(String relativeFilePath, String savePath)
   at BootstrapEmail.Net.BootstrapEmail.Compile(String input, String output, InputType type)
   at Program.<Main>$(String[] args) in /app/Program.cs:line 7
--- End of stack trace from previous location ---
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.IO.StreamWriter.<FlushAsyncInternal>g__Core|76_0(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)
   at System.IO.StreamWriter.WriteAsyncInternal(ReadOnlyMemory`1 source, Boolean appendNewLine, CancellationToken cancellationToken)
   at Citizen17.DartSass.DartSassRuntime.ExecuteAsync(String args, String input, CancellationToken cancellationToken)
   at Citizen17.DartSass.DartSassCompiler.CompileCodeAsync(String code, SassCompileOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at BootstrapEmail.Net.SassCache.CompileAndCacheScss(String cachePath)
   at BootstrapEmail.Net.SassCache.Compile()
   at BootstrapEmail.Net.SassCache.Compile(String type, Config config, StyleType style)
   at BootstrapEmail.Net.Compiler.InlineCss()
   at BootstrapEmail.Net.Compiler.PerformHtmlCompile()
   at BootstrapEmail.Net.Compiler.PerformFullCompile()
   at BootstrapEmail.Net.BootstrapEmail.FileCompile(String relativeFilePath, String savePath)
   at BootstrapEmail.Net.BootstrapEmail.Compile(String input, String output, InputType type)
   at Program.<Main>$(String[] args) in /app/Program.cs:line 7`

**Comment by w8tcha** [comment]
I tested it only with Ubuntu before. But now with your docker file and Alpine  i can reproduce this. 

In this case you need to use the  `DartSass.Native.linux-musl-x64` nuget package. Which as the moment is broken, because it doesnt copy the files. I submitted a pull request to the maintainer.

Also in the ConfigStore you need to set the DartSassNativeType manuallly because the musl linux can not be detected 
automatically.

```c#
var config = new ConfigStore { sass_email_location = "styles/", DartSassNativeType = DartSassNativeType.LinuxMuslX64 };
```

When the nuget package gets released i can release an updated version.

**Comment by w8tcha** [comment]
New version 1.5.1 is out, it should work now with your docker file.

**Comment by w8tcha** [comment]
Yes that is normal this cannot work. The dart-sass runtime are only copied to the library folder but from there not to the application which references the library. If you reference the bootstrapemail.net nuget package in the console application then it resolves the issue.
